# ============================================================
# IMPORT REQUIRED PYTHON AND LANGCHAIN LIBRARIES
# ============================================================

# sqlite3 is Python's built-in library for working with SQLite databases.
# We use it to save and load conversation history.
import sqlite3

# Path provides an easy way to work with file and folder paths.
# We use it to check whether the PDF file exists.
from pathlib import Path

# pdfplumber is used to open PDF files and extract text from their pages.
import pdfplumber

# HumanMessage represents a message sent by the user.
# AIMessage represents a message generated by the AI.
from langchain_core.messages import AIMessage, HumanMessage

# Document is a LangChain object used to store:
#   1. The actual text in page_content
#   2. Additional information in metadata
from langchain_core.documents import Document

# ChatPromptTemplate creates a structured chat prompt.
# MessagesPlaceholder allows us to insert previous conversation messages
# dynamically into the prompt.
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

# FAISS is a vector database/vector store.
# It stores embeddings and helps retrieve the most relevant PDF chunks.
from langchain_community.vectorstores import FAISS

# RecursiveCharacterTextSplitter splits large documents into smaller chunks.
from langchain_text_splitters import RecursiveCharacterTextSplitter

# HuggingFaceEmbeddings converts text into numerical vector embeddings.
from langchain_huggingface import HuggingFaceEmbeddings

# ChatOllama allows LangChain to communicate with a locally running
# Ollama language model.
from langchain_ollama import ChatOllama


# ============================================================
# APPLICATION CONFIGURATION
# ============================================================

# Absolute path of the PDF file that will be used as the knowledge source.
PDF_PATH = r"C:\Users\abc\Downloads\abc.pdf"

# Name of the SQLite database file.
# This database will store all conversation messages.
DATABASE_PATH = "chat_history.db"

# Hugging Face embedding model used to convert text into vectors.
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

# Name of the Ollama model that will generate answers.
OLLAMA_MODEL = "qwen3:8b"

# Maximum approximate size of each text chunk.
CHUNK_SIZE = 800

# Number of characters shared between consecutive chunks.
# This helps preserve context between chunks.
CHUNK_OVERLAP = 150

# Number of relevant document chunks to retrieve for each question.
TOP_K = 4


# ============================================================
# CREATE SQLITE DATABASE AND CHAT HISTORY TABLE
# ============================================================

def create_database():
    """
    Creates the SQLite database and the chat_history table.

    If the database file does not already exist, SQLite creates it.

    If the chat_history table already exists,
    CREATE TABLE IF NOT EXISTS prevents an error and keeps
    the existing conversation data.
    """

    # Connect to the SQLite database.
    # If chat_history.db does not exist, SQLite creates it.
    connection = sqlite3.connect(DATABASE_PATH)

    # Create a cursor object.
    # The cursor is used to execute SQL commands.
    cursor = connection.cursor()

    # Create the chat_history table if it does not already exist.
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS chat_history (

            -- Automatically generated unique ID for every message.
            id INTEGER PRIMARY KEY AUTOINCREMENT,

            -- Identifies which conversation/session the message belongs to.
            session_id TEXT NOT NULL,

            -- Stores who created the message.
            -- In our program, this will be either:
            -- "human" or "ai".
            role TEXT NOT NULL,

            -- Stores the actual text of the question or answer.
            message TEXT NOT NULL
        )
    """)

    # Commit/save the database changes permanently.
    connection.commit()

    # Close the database connection after the operation is complete.
    connection.close()


# ============================================================
# SAVE ONE MESSAGE INTO SQLITE
# ============================================================

def save_message(session_id, role, message):
    """
    Saves one message into the SQLite database.

    Parameters:
        session_id:
            Identifies which conversation the message belongs to.

        role:
            Identifies who sent the message.

            Possible values in this application:
                - "human"
                - "ai"

        message:
            The actual question or answer text.
    """

    # Connect to the SQLite database.
    connection = sqlite3.connect(DATABASE_PATH)

    # Create a cursor for executing SQL commands.
    cursor = connection.cursor()

    # Insert one new message into the chat_history table.
    #
    # The ? symbols are SQL placeholders.
    # The actual values are provided separately as a tuple.
    #
    # This is safer than directly inserting variables into the SQL string.
    cursor.execute(
        """
        INSERT INTO chat_history (session_id, role, message)
        VALUES (?, ?, ?)
        """,
        (session_id, role, message)
    )

    # Save the inserted message permanently.
    connection.commit()

    # Close the database connection.
    connection.close()


# ============================================================
# LOAD PREVIOUS CHAT HISTORY FOR ONE SESSION
# ============================================================

def load_chat_history(session_id):
    """
    Loads all previous messages belonging to the given session ID.

    The messages are read from SQLite and converted into
    LangChain message objects:

        "human" --> HumanMessage
        "ai"    --> AIMessage

    The function returns a list of LangChain messages.
    """

    # Connect to the SQLite database.
    connection = sqlite3.connect(DATABASE_PATH)

    # Create a cursor to execute SQL commands.
    cursor = connection.cursor()

    # Select all messages belonging only to the current session.
    #
    # ORDER BY id ASC ensures that messages are returned in
    # the same order in which they were saved.
    cursor.execute(
        """
        SELECT role, message
        FROM chat_history
        WHERE session_id = ?
        ORDER BY id ASC
        """,
        (session_id,)
    )

    # fetchall() retrieves all matching rows from the SQL query.
    #
    # Example:
    #
    # [
    #     ("human", "Who is the CEO?"),
    #     ("ai", "John Smith is the CEO.")
    # ]
    rows = cursor.fetchall()

    # Close the database connection because we have already
    # retrieved all the required rows.
    connection.close()

    # Create an empty list that will contain LangChain message objects.
    messages = []

    # Loop through every row returned from the database.
    #
    # Each row contains two values:
    #     role
    #     message
    for role, message in rows:

        # If the message was originally sent by the user,
        # create a HumanMessage object.
        if role == "human":

            messages.append(
                HumanMessage(content=message)
            )

        # If the message was generated by the AI,
        # create an AIMessage object.
        elif role == "ai":

            messages.append(
                AIMessage(content=message)
            )

    # Return the complete conversation history as a list
    # of LangChain message objects.
    return messages


# ============================================================
# LOAD PDF AND CONVERT EACH PAGE INTO A DOCUMENT OBJECT
# ============================================================

def load_pdf(pdf_path):
    """
    Opens the PDF and extracts text from every page.

    Each page containing text is converted into a LangChain
    Document object.

    Each Document contains:

        page_content:
            The text extracted from that PDF page.

        metadata:
            Additional information about the text.

            Here, we store the PDF page number.

    Returns:
        A list of Document objects.
    """

    # Create an empty list to store Document objects.
    documents = []

    # Open the PDF file.
    #
    # The 'with' statement automatically closes the PDF
    # after processing is complete.
    with pdfplumber.open(pdf_path) as pdf:

        # Loop through every page in the PDF.
        #
        # enumerate() gives us both:
        #     page_number --> index number
        #     page        --> actual PDF page object
        #
        # By default, enumerate starts from 0.
        for page_number, page in enumerate(pdf.pages):

            # Extract text from the current PDF page.
            text = page.extract_text()

            # Continue only if text was successfully extracted.
            #
            # If text is None or empty, this condition is False
            # and that page is skipped.
            if text:

                # Create a LangChain Document object.
                documents.append(
                    Document(

                        # Store the extracted text.
                        page_content=text,

                        # Store additional information about
                        # where this text came from.
                        metadata={

                            # Add 1 because Python indexes pages
                            # starting from 0, while humans usually
                            # refer to the first page as page 1.
                            "page": page_number + 1
                        }
                    )
                )

    # Return the list of Document objects.
    return documents


# ============================================================
# CREATE FAISS VECTOR STORE
# ============================================================

def create_vector_store(documents):
    """
    Creates a FAISS vector store from the PDF documents.

    Process:

        Documents
            ↓
        Split into smaller chunks
            ↓
        Create embeddings for each chunk
            ↓
        Store embeddings in FAISS

    Returns:
        A FAISS vector store.
    """

    # Create a text splitter.
    #
    # RecursiveCharacterTextSplitter tries to split text using
    # different separators such as paragraphs and sentences
    # before splitting at smaller levels.
    text_splitter = RecursiveCharacterTextSplitter(

        # Approximate maximum size of each chunk.
        chunk_size=CHUNK_SIZE,

        # Number of characters repeated between consecutive chunks.
        # This helps preserve context at chunk boundaries.
        chunk_overlap=CHUNK_OVERLAP
    )

    # Split the original Document objects into smaller Document chunks.
    #
    # The resulting chunks preserve metadata from the original Documents,
    # such as the PDF page number.
    chunks = text_splitter.split_documents(documents)

    # Create the embedding model.
    #
    # This model converts text into numerical vectors.
    embeddings = HuggingFaceEmbeddings(

        # Name of the embedding model.
        model_name=EMBEDDING_MODEL,

        # Additional configuration for the model.
        model_kwargs={

            # Only use files already available locally.
            #
            # The model will not attempt to download files
            # from Hugging Face.
            "local_files_only": True
        }
    )

    # Create a FAISS vector store.
    #
    # FAISS will:
    #
    # 1. Take every chunk.
    # 2. Send it to the embedding model.
    # 3. Receive a numerical vector for each chunk.
    # 4. Build a searchable FAISS index.
    vector_store = FAISS.from_documents(

        # Document chunks that will be converted into vectors.
        documents=chunks,

        # Embedding model used to create those vectors.
        embedding=embeddings
    )

    # Return the FAISS vector store.
    return vector_store


# ============================================================
# CREATE THE LLM AND CHAT PROMPT
# ============================================================

def create_conversation_chain(vector_store):
    """
    Creates:

        1. The Ollama LLM.
        2. The chat prompt template.

    The vector_store parameter is passed to this function,
    although it is not directly used inside the current implementation.

    The actual retrieval from the vector store happens later
    inside ask_question().
    """

    # Create a ChatOllama object.
    #
    # This object communicates with the Ollama model running locally.
    llm = ChatOllama(

        # Name of the model installed in Ollama.
        model=OLLAMA_MODEL,

        # Controls randomness in the generated answer.
        #
        # temperature=0 means the model will try to be more
        # deterministic and less creative.
        temperature=0
    )

    # Create a structured chat prompt.
    #
    # The prompt contains:
    #
    # 1. System instructions.
    # 2. Previous conversation messages.
    # 3. The current user question.
    prompt = ChatPromptTemplate.from_messages([

        # ----------------------------------------------------
        # SYSTEM MESSAGE
        # ----------------------------------------------------
        #
        # This gives instructions to the LLM about how it
        # should answer.
        (
            "system",
            """
You are a helpful assistant answering questions about a PDF document.

Use the provided document context to answer the user's question.

If the answer is not available in the document context, say:

"I could not find that information in the document."

Previous conversation messages may help you understand references
such as "he", "she", "it", "they", or follow-up questions.

Document Context:
{context}
"""
        ),

        # ----------------------------------------------------
        # CHAT HISTORY PLACEHOLDER
        # ----------------------------------------------------
        #
        # This placeholder will be replaced with actual previous
        # HumanMessage and AIMessage objects at runtime.
        #
        # For example:
        #
        # Human: Who is the CEO?
        # AI: John Smith is the CEO.
        #
        MessagesPlaceholder(
            variable_name="chat_history"
        ),

        # ----------------------------------------------------
        # CURRENT HUMAN QUESTION
        # ----------------------------------------------------
        #
        # {question} will be replaced with the user's current
        # question when prompt.invoke() or chain.invoke() runs.
        (
            "human",
            "{question}"
        )
    ])

    # Return both objects.
    #
    # The calling code receives:
    #
    # llm    --> first return value
    # prompt --> second return value
    return llm, prompt


# ============================================================
# ASK ONE QUESTION AND GENERATE AN ANSWER
# ============================================================

def ask_question(
    question,
    session_id,
    vector_store,
    llm,
    prompt
):
    """
    Handles one complete question-answer cycle.

    Process:

        Current session ID
                ↓
        Load previous conversation from SQLite
                ↓
        Current user question
                ↓
        Search FAISS for relevant PDF chunks
                ↓
        Combine retrieved chunks into document context
                ↓
        Add:
            - document context
            - previous chat history
            - current question
                ↓
        Prompt
                ↓
        LLM
                ↓
        AI answer
                ↓
        Save question and answer to SQLite
                ↓
        Return answer
    """

    # Load all previous messages belonging to this session.
    #
    # The returned value is a list containing HumanMessage
    # and AIMessage objects.
    chat_history = load_chat_history(session_id)

    # Create a retriever from the FAISS vector store.
    #
    # The retriever is responsible for searching the vector store
    # and returning relevant Document objects.
    retriever = vector_store.as_retriever(

        # Use Maximal Marginal Relevance (MMR) retrieval.
        #
        # MMR attempts to retrieve documents that are:
        #     1. Relevant to the question.
        #     2. Not too similar/redundant with each other.
        search_type="mmr",

        # Configure retrieval settings.
        search_kwargs={

            # Retrieve TOP_K relevant chunks.
            "k": TOP_K
        }
    )

    # Search the FAISS vector store using the current question.
    #
    # The result is a list of Document objects.
    retrieved_documents = retriever.invoke(question)

    # Combine the text from all retrieved Document objects
    # into one string.
    #
    # "\n\n" adds two new lines between chunks.
    #
    # Example:
    #
    # Chunk 1 text
    #
    # Chunk 2 text
    #
    # Chunk 3 text
    context = "\n\n".join(

        # Get the actual text from each retrieved Document.
        document.page_content

        # Loop through every retrieved Document.
        for document in retrieved_documents
    )

    # Create an LCEL chain.
    #
    # The | operator connects the components.
    #
    # Data flow:
    #
    # Input dictionary
    #       ↓
    # prompt
    #       ↓
    # ChatPromptValue / formatted messages
    #       ↓
    # llm
    #       ↓
    # AIMessage
    chain = prompt | llm

    # Execute the chain.
    #
    # The dictionary provides actual values for the placeholders:
    #
    # {context}
    # {chat_history}
    # {question}
    response = chain.invoke({

        # Relevant chunks retrieved from the PDF.
        "context": context,

        # Previous questions and answers from this session.
        "chat_history": chat_history,

        # The user's current question.
        "question": question
    })

    # The LLM returns an AIMessage object.
    #
    # response.content contains the actual answer text.
    answer = response.content

    # Save the user's current question in SQLite.
    save_message(

        # Identify which conversation this message belongs to.
        session_id=session_id,

        # Identify this message as a user message.
        role="human",

        # Store the actual question.
        message=question
    )

    # Save the AI's answer in SQLite.
    save_message(

        # Use the same session ID so the answer belongs
        # to the same conversation.
        session_id=session_id,

        # Identify this message as an AI message.
        role="ai",

        # Store the generated answer.
        message=answer
    )

    # Return the answer to the function that called ask_question().
    return answer


# ============================================================
# MAIN APPLICATION FUNCTION
# ============================================================

def main():

    # --------------------------------------------------------
    # CHECK WHETHER THE PDF FILE EXISTS
    # --------------------------------------------------------

    # Create a Path object for the PDF and check whether
    # the file exists.
    if not Path(PDF_PATH).exists():

        # Inform the user that the PDF could not be found.
        print(f"\nPDF not found: {PDF_PATH}")

        # NOTE:
        # This message originally referred to a data folder,
        # but your PDF_PATH is actually an absolute path.
        # This message can be changed to match your setup.
        print(
            "\nPlease check the PDF_PATH and make sure "
            "the PDF file exists."
        )

        # Stop the main() function because the application
        # cannot continue without the PDF.
        return

    # --------------------------------------------------------
    # CREATE SQLITE DATABASE
    # --------------------------------------------------------

    # Create the database and chat_history table if needed.
    create_database()

    # --------------------------------------------------------
    # LOAD AND PROCESS THE PDF
    # --------------------------------------------------------

    # Inform the user that PDF processing has started.
    print("\nLoading PDF...")

    # Load the PDF and convert its pages into Document objects.
    documents = load_pdf(PDF_PATH)

    # Check whether any text was successfully extracted.
    if not documents:

        # Inform the user that no extractable text was found.
        print("\nNo text could be extracted from the PDF.")

        # Stop the application because there is no text
        # available to create embeddings.
        return

    # Inform the user that the vector store is being created.
    print("Creating vector store...")

    # Split documents, create embeddings, and build the FAISS index.
    vector_store = create_vector_store(documents)

    # --------------------------------------------------------
    # CREATE LLM AND PROMPT
    # --------------------------------------------------------

    # Create the Ollama LLM and chat prompt template.
    #
    # Python unpacking assigns:
    #
    # First returned value  --> llm
    # Second returned value --> prompt
    llm, prompt = create_conversation_chain(vector_store)

    # --------------------------------------------------------
    # ASK FOR A SESSION ID
    # --------------------------------------------------------

    # Print a heading for the application.
    print("\n" + "=" * 60)
    print("CONVERSATIONAL PDF RAG")
    print("=" * 60)

    # Ask the user to enter a session ID.
    #
    # .strip() removes extra spaces from the beginning
    # and end of the entered value.
    session_id = input(
        "\nEnter Session ID: "
    ).strip()

    # If the user presses Enter without entering a session ID,
    # assign a default session ID.
    #
    # This prevents all database operations from using an
    # empty string as the session ID.
    if not session_id:
        session_id = "default"

    # Display which session is currently active.
    print(
        f"\nConversation started for session: {session_id}"
    )

    # Tell the user how to end the conversation.
    print(
        "Type 'exit' or 'quit' to stop the conversation.\n"
    )

    # --------------------------------------------------------
    # CONVERSATION LOOP
    # --------------------------------------------------------

    # while True creates an infinite loop.
    #
    # The loop continues until we explicitly use break.
    while True:

        # Ask the user to enter a question.
        #
        # .strip() removes unnecessary spaces from the beginning
        # and end of the question.
        question = input("You: ").strip()

        # Convert the question to lowercase and check whether
        # the user wants to stop the application.
        #
        # .lower() allows:
        #     EXIT
        #     Exit
        #     exit
        #
        # to all be treated the same.
        if question.lower() in ["exit", "quit"]:

            # Inform the user that the conversation has ended.
            print("\nConversation ended.")

            # Exit the while True loop.
            break

        # If the user entered an empty question,
        # immediately start the next loop iteration.
        if not question:
            continue

        # Process the question.
        #
        # ask_question() will:
        #
        # 1. Load previous chat history from SQLite.
        # 2. Search FAISS for relevant PDF chunks.
        # 3. Create the document context.
        # 4. Add chat history.
        # 5. Add the current question.
        # 6. Send everything through prompt | llm.
        # 7. Save the question and answer to SQLite.
        # 8. Return the answer.
        answer = ask_question(
            question=question,
            session_id=session_id,
            vector_store=vector_store,
            llm=llm,
            prompt=prompt
        )

        # Display the AI's answer.
        print(f"\nAI: {answer}\n")


# ============================================================
# PROGRAM ENTRY POINT
# ============================================================

# __name__ is a special Python variable.
#
# When this file is run directly:
#
#     python filename.py
#
# Python sets:
#
#     __name__ = "__main__"
#
# Therefore, main() is executed.
#
# If this file is imported into another Python file,
# main() will not run automatically.
if __name__ == "__main__":
    main()